# Generated by Django 4.1.4 on 2022-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('about', models.TextField()),
                ('image_url', models.ImageField(upload_to='img')),
            ],
        ),
    ]
